# Generated by Django 3.0.5 on 2020-05-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('geo_heading', models.CharField(max_length=250)),
                ('geo_body', models.TextField()),
            ],
        ),
    ]
