version: '3.3'

services:
  backend: &backend
    image: 0.0.0.0:5000/geo-backend
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend/
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
    tty: true
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env

  nginx:
    image: 0.0.0.0:5000/geo-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
    labels:
      - "traefik.enable=true"
      - 'traefik.frontend.rule=Host:www.ec2-18-188-120-148.us-east-2.compute.amazonaws.com'
      - "traefik.port=80"

  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: 0.0.0.0:5000/geo-traefik
    depends_on:
      - backend
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  postgres:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    image: 0.0.0.0:5000/geo-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backups:/var/lib/postgresql/backups/
    env_file: .env

  redis:
    image: redis:latest
    volumes:
      - redisdata:/data

volumes:
  postgres_data: {}
  backups: {}
  redisdata: {}
  traefik: {}