version: '3.3'

services:
  backend: &django
    image: elvinos/geo:geo-backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend/
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
    command: /gunicorn.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file: .env
    ports:
     - "8080:8080"
    networks:
      - backend_net

  nginx:
    image: elvinos/geo:geo-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: on-failure
    logging:
      driver: none
    networks:
      - backend_net

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backups:/var/lib/postgresql/backups/
    env_file: .env
    restart: on-failure
    networks:
      - backend_net

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend_net

  celeryworker:
    <<: *django
    image: celeryworker
    working_dir: /backend
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
    networks:
      - backend_net

  celerybeat:
    <<: *django
    image: celerybeat
    working_dir: /backend
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat
    networks:
      - backend_net

  flower:
    <<: *django
    image: flower
    working_dir: /backend
    ports:
      - "5555:5555"
    command: /start-flower
    networks:
      - backend_net

volumes:
  postgres_data:
  backups:
  redisdata:

networks:
  backend_net: