version: '3.3'

services:
  backend:
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend/
#      - ./backend/media/:/media/
#      - ./backend/staticfiles/:/staticfiles/
    tty: true
    command: /dev_start.sh
    entrypoint: /entrypoint.sh
#    restart: on-failure
    env_file: .env
    networks:
      - backend_net

  frontend:
    image: node:12-alpine
    command: yarn serve
    volumes:
      - ./frontend:/app
    working_dir: /app
    env_file: .env
    restart: on-failure
    networks:
      - backend_net

  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - backups:/var/lib/postgresql/backups/
    env_file: .env
    networks:
      - backend_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./backend/media/:/media/
      - ./backend/staticfiles/:/staticfiles/
      - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: none
    networks:
      - backend_net

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  postgres_data:
  backups:
  redisdata:

networks:
  backend_net: